[package]
name = "mem_dbg"
version = "0.1.0"
edition = "2021"
description = "Traits and derives to get infos about the memory usage of a struct"
repository = "https://github.com/zommiommy/mem_dbg/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["allocation", "debug", "memory"]
authors = ["Tommaso Fontana <tommaso.fontana.96@gmail.com>", "Sebastiano Vigna <sebastiano.vigna@unimi.it>"]

[dependencies]
mmap-rs = {version="0.5.0", optional=true}

[features]
default = ["std", "mmap-rs", "derive"]
derive = ["mem_dbg-derive"]
std = ["alloc"]
alloc = []
