[package]
name = "mem_dbg"
version = "0.1.1"
edition = "2021"
description = "Traits and associated procedural macros to display recursively the layout and memory usage of a value"
repository = "https://github.com/zommiommy/mem_dbg/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["allocation", "debug", "memory"]
authors = ["Tommaso Fontana <tommaso.fontana.96@gmail.com>", "Sebastiano Vigna <sebastiano.vigna@unimi.it>"]

[dependencies]
mmap-rs = {version="0.6.0", optional=true}
mem_dbg-derive = { version = "=0.1.0", optional = true }
bitflags = "2.4.1"

[features]
default = ["std", "mmap-rs", "derive"]
derive = ["mem_dbg-derive"]
std = ["alloc"]
alloc = []
