name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run no default features tests
        run: cargo test --verbose --no-default-features
      - name: Run tests with alloc feature
        run: cargo test --verbose --no-default-features --features alloc
      - name: Run examples
        working-directory: ./mem_dbg
        run: for example in examples/*.rs ; do cargo run --example "$(basename "${example%.rs}")" ; done
      - name: Run clippy
        run: cargo clippy #-- -Dclippy::all -Dclippy::cargo